name: Auto-deployment of Documentation
on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Set env
        run: echo "PROJECT_DIR=${{ github.workspace }}/src/wf_test" >> $GITHUB_ENV

      - name: Call BBOP standard workflow
        uses: hrshdhgd/qc-action@main
        with:
          python-versions: "3.9"
          workflow-type: docs
          token: ${{ secrets.GH_TOKEN }}

      