name: Auto-deployment of Documentation
on:
  push:
    branches: [ main ]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Call standard workflow
        uses: hrshdhgd/qc-action@main
        with:
          python-versions: "3.9"
          use-tox: true
          workflow-type: docs
          token: ${{ secrets.GH_TOKEN }}