# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v3

      - name: Call BBOP standard workflow
        uses: hrshdhgd/qc-action@main
        with:
          python-versions: ${{ matrix.python-version }}
          use-tox: true
          workflow-type: qc
